// <auto-generated />
using FelipeShopping.ProdutoAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FelipeShopping.ProdutoAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20220122184041_AdicionarProdutosNaTabela")]
    partial class AdicionarProdutosNaTabela
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FelipeShopping.ProdutoAPI.Model.Produto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoriaNome")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("categoria_nome");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("imagem_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("produto");

                    b.HasData(
                        new
                        {
                            Id = 15L,
                            CategoriaNome = "Camiseta",
                            Descricao = "Felipe Descricao_15",
                            ImagemUrl = "http://felipeproduto.com/15",
                            Nome = "Felipe_15",
                            Valor = 899.85m
                        },
                        new
                        {
                            Id = 16L,
                            CategoriaNome = "Camiseta",
                            Descricao = "Felipe Descricao_16",
                            ImagemUrl = "http://felipeproduto.com/16",
                            Nome = "Felipe_16",
                            Valor = 3199.84m
                        },
                        new
                        {
                            Id = 17L,
                            CategoriaNome = "Camiseta",
                            Descricao = "Felipe Descricao_17",
                            ImagemUrl = "http://felipeproduto.com/17",
                            Nome = "Felipe_17",
                            Valor = 3399.83m
                        },
                        new
                        {
                            Id = 18L,
                            CategoriaNome = "Shorts",
                            Descricao = "Felipe Descricao_18",
                            ImagemUrl = "http://felipeproduto.com/18",
                            Nome = "Felipe_18",
                            Valor = 3599.82m
                        },
                        new
                        {
                            Id = 19L,
                            CategoriaNome = "Shorts",
                            Descricao = "Felipe Descricao_19",
                            ImagemUrl = "http://felipeproduto.com/19",
                            Nome = "Felipe_19",
                            Valor = 3799.81m
                        },
                        new
                        {
                            Id = 20L,
                            CategoriaNome = "Shorts",
                            Descricao = "Felipe Descricao_20",
                            ImagemUrl = "http://felipeproduto.com/20",
                            Nome = "Felipe_20",
                            Valor = 3999.8m
                        },
                        new
                        {
                            Id = 21L,
                            CategoriaNome = "Bones",
                            Descricao = "Felipe Descricao_21",
                            ImagemUrl = "http://felipeproduto.com/21",
                            Nome = "Felipe_21",
                            Valor = 4199.79m
                        },
                        new
                        {
                            Id = 22L,
                            CategoriaNome = "Bones",
                            Descricao = "Felipe Descricao_22",
                            ImagemUrl = "http://felipeproduto.com/22",
                            Nome = "Felipe_22",
                            Valor = 4399.78m
                        },
                        new
                        {
                            Id = 23L,
                            CategoriaNome = "Bones",
                            Descricao = "Felipe Descricao_23",
                            ImagemUrl = "http://felipeproduto.com/23",
                            Nome = "Felipe_23",
                            Valor = 4599.77m
                        },
                        new
                        {
                            Id = 24L,
                            CategoriaNome = "Livro",
                            Descricao = "Felipe Descricao_24",
                            ImagemUrl = "http://felipeproduto.com/24",
                            Nome = "Felipe_24",
                            Valor = 4799.76m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
